name: release

on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.RELEASE_PAT }}
    - env:
        GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
        GIT_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
        GIT_COMMITTER_NAME: ${{ github.event.head_commit.author.name }}
        GIT_COMMITTER_EMAIL: ${{ github.event.head_commit.author.email }}
      run: |
        sh release.sh
